### ISSUE TITLE
Downloading empty file

### ISSUE THREAD

**Issue by cryptopsy30** [xxcodianxx/youtube-dl-web#20] opened 2022-08-21 16:52 UTC
Fetching metadata works.
Then downloading with any option gives empty files.

**Comment by xxcodianxx** [comment] 2022-08-21 22:13
Going to investigate this, thanks for the issue.

**Comment by DavidBerdik** [comment] 2022-08-22 01:39
@xxcodianxx I am encountering the same issue on my stripped-down fork of this project. If time permits and I find a solution before you get to it, I will let you know.

**Comment by xxcodianxx** [comment] 2022-08-22 01:57
I can't seem to reproduce this bug locally on the provided Docker containers, everything downloads fine, but I can obviously see this is a real issue...

@cryptopsy30 Can you provide a link to an example video that doesn't download properly? The problem may be localized to only some videos/edge cases.
@DavidBerdik Thanks for your help!

**Comment by DavidBerdik** [comment] 2022-08-22 02:09
@xxcodianxx You're welcome! The issue seems to be caused by yt-dlp version 2022.08.19. I've been able to get the `dl` endpoint working for `best`, `bestaudio`, and `bestvideo`, but it's still broken for `bestvideo+bestaudio`.

The changes I made to get it working are in my repo [here](https://github.com/DavidBerdik/YouTube-Stream-Repeater/commit/2b85d7ff2b501f4b49202befefc10032083baa40).

**Comment by xxcodianxx** [comment] 2022-08-22 04:22
`bestaudio+bestvideo` also seems to work with this change, make sure to urlescape `+` properly as `%2B`

Committed some extra stuff, but 75e0b3dee143865c0f0e59ad99707650b09f7f6d should fix it. Let me know how it goes.

**Comment by cryptopsy30** [comment] 2022-08-22 13:12
Thanks @xxcodianxx the patch fixed it for me. The video I was testing with was D5vqvPaMCLg.

It is now downloading the file in .webm. Would it be possible to add the option to download in more format such as .mp3 when selecting audio only?

Thank you for your effort. I love this project.

**Comment by xxcodianxx** [comment] 2022-08-22 21:35
Glad that it works! As for reformatting into mp3, well it's complicated. 

Right now I'm returning the exact thing youtube sends over, in the container that requires least transcoding.

If you hover over the different audio options, you'll notice some are mp4a. These download as mp4 files, but I may be able to make them into mp3's without sacrificing speed.

Marking this issue as closed, thanks everyone!

**Closed** 2022-08-22 21:35 UTC
Labels: bug

**Comment by DavidBerdik** [comment] 2022-08-22 21:54
> `bestaudio+bestvideo` also seems to work with this change, make sure to urlescape `+` properly as `%2B`
> 
> Committed some extra stuff, but [75e0b3d](https://github.com/xxcodianxx/youtube-dl-web/commit/75e0b3dee143865c0f0e59ad99707650b09f7f6d) should fix it. Let me know how it goes.

@xxcodianxx Ah yes! That was it! I can't believe I forgot about that. I should know better. Anyway, it seems to be working for me as well.

**Comment by DavidBerdik** [comment] 2022-08-22 22:19
@xxcodianxx Even though it's working for me, I do have a question: I noticed that after the changes you made, hitting the `dl` endpoint with a browser no longer results in in-browser playback. Instead, the stream starts downloading. What is the reason for this change?

**Comment by xxcodianxx** [comment] 2022-08-22 22:21
It may be because I'm properly setting the content-disposition header now.

This is probably somehow related to d7f76fd002b4b5942ec8c98d09d937c863623bbd

**Comment by DavidBerdik** [comment] 2022-08-22 22:37
@xxcodianxx Got it. Thank you!
